# MongoDB 8.0 specific variables
# Include this file in your playbook to use MongoDB 8.0

# MongoDB version
mongo_version: '8.0'

# Basic configuration
mongo_enable_replication: true
mongo_enable_security: true
