---
- name: copy createUsers script
  template: src=createUsers.j2 dest=/tmp/createUsers.js

- name: create users
  shell: mongosh {{ansible_default_ipv4.address}}:{{mongo_port}}  < /tmp/createUsers.js  
